name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev/* ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt
    - run: pytest -sv test/config

  test-endpoints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt
    - run: pytest -sv test/endpoints

  test-clients:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt
    - run: pytest -sv test/clients
      env:
        PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/tools
