name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev/* ]
  release:
    types: [created]
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/tools

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: ruff check . --exclude tools/

  test-config:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/config

  test-endpoints:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/endpoints

  test-clients:
    runs-on: ubuntu-latest
    needs: lint
    steps:

    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt

    - name: Build logger-client image (with cache)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: examples/clients/logger.Dockerfile
        tags: logger-client
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - run: pytest -sv test/clients

  coverage:
    runs-on: ubuntu-latest
    needs: [test-config, test-endpoints, test-clients]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt

    - name: Build logger-client image (with cache)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: examples/clients/logger.Dockerfile
        tags: logger-client
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - run: pytest --cov=src --cov-fail-under=90 test

  encryption-wrapper:
    uses: ./.github/workflows/encryption_wrapper_ci.yml
