name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev/* ]
  release:
    types: [created]
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/tools

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/domayre/confidential-server/devcontainer
        cacheFrom: ghcr.io/domayre/confidential-server/devcontainer
        push: always

  lint:
    runs-on: ubuntu-latest
    needs: devcontainer
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: ruff check . --exclude tools/

  test-config:
    runs-on: ubuntu-latest
    needs: [lint, devcontainer]
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/config

  test-endpoints:
    runs-on: ubuntu-latest
    needs: [lint, devcontainer]
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/endpoints

  test-clients:
    runs-on: ubuntu-latest
    needs: [lint, devcontainer]
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/clients

  coverage:
    runs-on: ubuntu-latest
    needs: [test-config, test-endpoints, test-clients]
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest --cov=src --cov-fail-under=90 test

  encryption-wrapper:
    uses: ./.github/workflows/tools_encryption_wrapper_ci.yml
    needs: devcontainer

  c-aci-attestation:
    uses: ./.github/workflows/tools_c_aci_attestation_ci.yml
    needs: devcontainer
