name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev/* ]
  release:
    types: [created]
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/tools

jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/config

  test-endpoints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/endpoints

  test-clients:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv test/clients

  test-encryption-wrapper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest -sv tools/encryption_wrapper/test

  lint-ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: ruff check .

  coverage:
    runs-on: ubuntu-latest
    needs: [test-config, test-endpoints, test-clients, test-encryption-wrapper, ruff-lint]
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r test/requirements.txt -r tools/**/requirements.txt
    - run: pytest --cov=. --cov-fail-under=90
