name: Release

on:
  pull_request:
  release:
    types: [created]

jobs:
  c-aci-attestation:
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/tools_c_aci_attestation_release.yml
