name: Release

on:
  pull_request:
  release:
    types: [created]

jobs:
  c-aci-attestation:
    permissions:
      packages: write
    uses: ./.github/workflows/tools_c_aci_attestation_release.yml
    with:
      version: ${{ github.event.release.tag_name || 'latest' }}
