name: C-ACI Attestation

on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_unit

  system:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_system

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_docker