name: C-ACI Attestation

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation lint

  unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_unit

  system:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_system

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_docker

  python:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test_python

  coverage:
    runs-on: ubuntu-latest
    needs: [unit, system, docker, python]
    steps:
    - uses: actions/checkout@v4
    - uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/domayre/confidential-server/devcontainer:latest
        cacheFrom: ghcr.io/domayre/confidential-server/devcontainer:latest
        push: always
        runCmd: |
          make -C tools/c-aci-attestation coverage