name: C-ACI Attestation

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version to release'
        required: true

env:
  TAG: ${{ github.run_id }}-${{ github.run_attempt }} # Use a dummy tag when testing

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: make -C tools/c-aci-attestation docker
    - run: make -C tools/c-aci-attestation test-docker

    - run: |
        . tools/c-aci-testing/.env
        DEPLOYMENT_NAME=$TAG make -C tools/c-aci-attestation test-aci

    - run: TAG=${{ inputs.version }} make -C tools/c-aci-attestation release-docker
