name: C-ACI Attestation

on:
  workflow_call:

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: make -C tools/c-aci-attestation docker
    - run: make -C tools/c-aci-attestation test-docker
    - run: make -C tools/c-aci-attestation release-docker
