name: C-ACI Attestation

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation lint

  unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test-unit

  system:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test-system

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test-docker

  python:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation test-python

  coverage:
    runs-on: ubuntu-latest
    needs: [unit, system, docker, python]
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation coverage

  address-sanitizer:
    runs-on: ubuntu-latest
    needs: [unit, system, docker, python]
    steps:
    - uses: actions/checkout@v4
    - run: make -C tools/c-aci-attestation asan
